# Generated by Django 2.0.13 on 2019-02-27 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='publishedDate',
        ),
    ]
