# Generated by Django 2.0.13 on 2019-02-28 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_post_publisheddate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='commentDislikes',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='commentLikes',
        ),
    ]
