# Generated by Django 2.0.13 on 2019-05-16 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190228_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='postImage',
            field=models.ImageField(default='media/default.png', upload_to='blog_post_images'),
        ),
    ]
