# Generated by Django 2.0.13 on 2019-05-16 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190516_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postImage',
            field=models.ImageField(default='media/default.png', upload_to='media/blog_post_images/'),
        ),
    ]
