# Generated by Django 2.0.13 on 2019-05-16 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190516_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postImage',
            field=models.ImageField(blank=True, default='media/default.png', upload_to='blog_post_images/'),
        ),
    ]
