# Generated by Django 2.0.13 on 2019-05-16 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20190516_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postImage',
            field=models.ImageField(blank=True, default='default.png', upload_to='blog_post_images/'),
        ),
    ]
